---
- name: Set up dependencies
  hosts: vmadd
  become: yes
  become_method: sudo
  become_user: root
  remote_user: bart
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install postgresql and pip3
      apt:
        update_cache: yes
        name:
          - postgresql
          - python3-pip
          - libpq-dev
        state: latest

    - name: Install flask dot-env and psycopg2
      pip:
        name:
          - python-dotenv
          - flask
          - psycopg2
        executable: pip3

    - name: Copy app
      copy:
        src: ./app
        dest: /home/bart
    
    - name: Create user
      become: yes
      become_user: postgres
      postgresql_user:
        name: "bart"
        password: "psql123"

    - name: Create database
      become: yes
      become_user: postgres
      postgresql_db:
        name: "my_db"
        owner: "bart"

    - name: Start flask
      shell: python3 app.py
      args:
        chdir: /home/bart/app
      environment:
        FLASK_RUN_PORT: 4000